CREATE TABLE films IF NOT EXISTS(
        film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(40) NOT NULL,
        description varchar(200) NOT NULL,
        release_data date NOT NULL,
        duration integer,
        rating varchar(10)
);

CREATE TABLE film_genre IF NOT EXISTS(
	film_id INTEGER REFERENCES films (film_id),
	genre_id INTEGER REFERENCES genre (genre_id),
	PRIMARY KEY (film_id,genre_id)
);

CREATE TABLE genre  IF NOT EXISTS(
genre_id int not null primary key auto_increment,
name varchar(255),
constraint GENRE_PK primary key (genre_id)
);

CREATE TABLE users  IF NOT EXISTS (
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(20) NOT NULL,
	login varchar(20) NOT NULL,
	name varchar(20),
	birthday date NOT NULL
);

CREATE TABLE likes IF NOT EXISTS(
	film_id INTEGER REFERENCES films (film_id),
	user_id INTEGER REFERENCES users (user_id),
	PRIMARY KEY (user_id,film_id)
);

CREATE TABLE friends IF NOT EXISTS(
	user_id INTEGER REFERENCES users (user_id),
	friend_id INTEGER REFERENCES users (user_id),
	status varchar(10),
	PRIMARY KEY (USER_ID,FRIEND_ID)
);